#!/usr/bin/env ruby

ignore 'web'

#
# Run thin server to give site a spin.
#
desc "start thin server"
task "server" do
  sh "thin start -A file"
end

#
# Compile Handlebar.js templates.
#
desc "compile templates"
task 'compile' do
  sh "handlebars assets/templates/*.handlebars -f assets/javascripts/handlebars.templates.js"
end

#
# The publish task uses the detroit-github plugin
# from the Detroit project.
#
desc 'publish website'
task 'publish' do
  # TODO: convert to file rules
  #mkdir_p 'web' unless directory?('web')
  #cp   'index.html', 'web/index.html'
  #cp   'doc.json',   'web/doc.json'
  #cp_r 'assets',     'web'

  github.publish
end

#
#
#
desc 'prepare website'
task 'prepare' do
  github.prepare
end

#
#
#
def github
  @github ||= (
    require 'detroit'
    require 'detroit-github'
 
    Detroit::GitHub.new(
      :folder  => 'web',
      :sitemap => {
        'index.html' => 'index.html',
        'doc.json'   => 'doc.json',
        'assets'     => 'assets'
      }
    )
  ) 
end
